---
name: "Playback Reporting"
guid: "5c534381-91a3-43cb-907a-35aa02eb9d2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-playbackreporting.png"
version: 14
targetAbi: "10.8.4.0"
framework: net6.0
owner: "jellyfin"
overview: "Collect and show user play statistics"
description: "Collect and show user play statistics"
category: "General"
artifacts:
  - "Jellyfin.Plugin.PlaybackReporting.dll"
changelog: |2-
  ### New features and improvements ###
  - Order default query usefully & checkbox by default (#66) @michaelkrieger
